# built following
# http://ehaselwanter.com/en/blog/2014/05/08/using-test-kitchen-with-puppet/
# and ported concepts from test-kitchen using chef
---
driver:
  provision: true

provisioner:
  name: puppet_apply
  manifests_path: manifests
  manifest: local.pp
  modules_path: modules
  hiera_data_path: data_testing
  hiera_deep_merge: true
  puppet_verbose: true
  puppet_debug: false
  require_chef_for_busser: false
  require_puppet_repo: false
  custom_options: '--show_diff'
  verify_host_key: false
  hiera_config_path: "hiera-testing.yaml"
  #custom_options: '--show_diff --debug'
  #custom_options: '--show_diff --noop'

transport:
  name: sftp

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: ubuntu-desktop
    driver_plugin: vagrant
    driver_config:
      customize:
        audio: "none"
    driver:
      vagrantfile_erb: vagrantfiles/Vagrantfile-debianoid.erb
      box: bento/ubuntu-18.04
      box_url: https://app.vagrantup.com/bento/boxes/ubuntu-18.04
      customize: 
        memory: 4096
      gui: true
      synced_folders:
        - ['./files', '/tmp/files']
      #network:
      #- ['private_network', {ip: '192.168.33.33'}]
      #- ["forwarded_port", {guest: 8080, host: 8080}]
      #

suites:
  - name: default
